version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: versbottomlex-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: versbottomlex
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - versbottomlex-network

  # Node.js Backend API
  api:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: versbottomlex-api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: versbottomlex
      JWT_SECRET: your_super_secret_token_here
      JWT_EXPIRE: 24h
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - versbottomlex-network

  # Flutter Web Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: versbottomlex-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ../frontend:/app
      - /app/build
    networks:
      - versbottomlex-network
    depends_on:
      - api

  # Nginx Proxy
  nginx:
    image: nginx:alpine
    container_name: versbottomlex-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build/web:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - frontend
    networks:
      - versbottomlex-network

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: versbottomlex-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d versbottomlex.me -d www.versbottomlex.me

networks:
  versbottomlex-network:
    driver: bridge

volumes:
  postgres_data:
